export {
  assertValidGraphIRDocument,
  GraphIRValidationError,
  collectLeafNodes,
  collectNeuronNodes,
  collectSignalNodes,
  summarizeGraphIRDocument,
  validateGraphIRDocument,
} from './legacyGraphIRSchema';

export type {
  AdapterNode,
  AggregateLinkView,
  GraphIRDocument,
  GraphIRValidationIssue,
  LeafLink,
  LiteralValue,
  ModelDefinition,
  NeuronGroupNode,
  NeuronNode,
  PortDefinition,
  RootGraph,
  SignalDefinition,
  SignalNode,
  TopologyNode,
  ValidatedGraphIRDocument,
  ValidatedRootGraph,
  ValidatedTopologyNode,
  VariableDefinition,
} from './legacyGraphIRSchema';
